### ISSUE TITLE
Error assigning the argument

### ISSUE THREAD

**Issue by harshraj22** [shan18/Depth-Estimation-Segmentation#2]
https://github.com/shan18/Depth-Estimation-Segmentation/blob/a4161979beb6ffa9561f4cbe8a2ffa0e06fca74e/tensornet/model/loss/dice.py#L19

Shouldn't it be:
```python
self.smooth = smooth
```
As we are accepting the `smooth` value as an argument ?

Please let me know if the repo is open for open source contribution. I could help in the following way:

- crosscheck the whole code
- Write unit tests to ensure such mistakes aren't hidden
- Write type hints, so that MyPy is happy 😁

**Comment by shan18** [comment]
Thanks for reporting this issue. I have fixed it.

Yes, the repo is open to accept contributions.

If you want to contribute, I'll be happy to merge the pull requests but just to let you know that I don't plan to add any new features or improve the model accuracy any further in this project.
